use_frameworks!

platform :ios, '13.0'

target 'TextWithImageView_Example' do
  pod 'TextWithImageView', :path => '../'

  target 'TextWithImageView_Tests' do
    inherit! :search_paths

    
  end
end
